Add contextualization mixin
MaelAudren/dsl-connector pull request #2
Opened 2016-10-27 12:47 UTC by MaelAudren

2016-10-27 14:13 UTC, fviale requested changes

2016-10-27 14:13 UTC, fviale commented on src/main/java/org/ow2/proactive/procci/model/occi/infrastructure/mixin/Contextualization.java
> +    public Contextualization(String title, List<Mixin> depends, List<Entity> entities, String userdata) {
You should update as well the javadoc after changing parameter names

2016-10-27 14:13 UTC, fviale commented on src/main/java/org/ow2/proactive/procci/model/occi/metamodel/MixinBuilder.java
> +            throw new SyntaxException(attribute.toString());
rename the method : convertAttributeAsString 
It is super weird to catch a ClassCastException ! You can eventually use instanceof . 

Additionally, if the attribute has a wrong type, you will not see in the Exception thrown which attribute key generated the error.

This is why I would suggest to write rather a method like:
readAttributeAsString(Map attributes, String key) which would be able to throw an understandable error message.

2016-10-27 15:10 UTC, fviale commented on src/main/java/org/ow2/proactive/procci/model/occi/metamodel/MixinBuilder.java
> +                throw new SyntaxException(key);
I think you should throw a message with a bit more explanation:
like: "invalid content type received for key " + key + ", expected String, received " + value.get().getClass().getTypeName()

2016-10-28 10:08 UTC, ShatalovYaroslav approved these changes

2016-11-03 13:16 UTC, merged